# Generated by Django 3.1.3 on 2021-02-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('professor1', models.CharField(blank=True, max_length=100, null=True)),
                ('professor2', models.CharField(blank=True, max_length=100, null=True)),
                ('day1', models.CharField(blank=True, max_length=1, null=True)),
                ('day2', models.CharField(blank=True, max_length=1, null=True)),
                ('day3', models.CharField(blank=True, max_length=1, null=True)),
                ('day4', models.CharField(blank=True, max_length=1, null=True)),
                ('start_h1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_m1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_h1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_m1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_h2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_h2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_m3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_h3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_h3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_m3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_h4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_m4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_h4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fin_m4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time1', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time2', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time3', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time4', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_time1', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_time2', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_time3', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_time4', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ManyToManyField(to='timetable.SubjectInfo')),
            ],
        ),
    ]
