# Generated by Django 3.1.3 on 2021-02-07 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='choice',
            field=models.ManyToManyField(related_name='choice_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
