# Generated by Django 3.1.3 on 2021-02-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210207_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_add',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject_add',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.subjectinfo'),
            preserve_default=False,
        ),
    ]
