# Generated by Django 3.1.3 on 2021-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210205_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectinfo',
            old_name='professor',
            new_name='professor1',
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='professor2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
