# Generated by Django 3.1.3 on 2021-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210205_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='finish_time1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='finish_time2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='finish_time3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='finish_time4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='start_time1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='start_time2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='start_time3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='start_time4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
