# Generated by Django 3.1.3 on 2021-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210207_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_add',
            old_name='subject',
            new_name='subject_add',
        ),
    ]
