# Generated by Django 3.1.3 on 2021-02-08 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0004_auto_20210208_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_add',
            name='subject_add',
        ),
        migrations.AddField(
            model_name='subject_add',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subjectinfo'),
        ),
        migrations.AddField(
            model_name='subject_add',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_add', to='auth.user'),
            preserve_default=False,
        ),
    ]
