# Generated by Django 3.1.3 on 2021-02-08 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0005_auto_20210208_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_add',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_add', to=settings.AUTH_USER_MODEL),
        ),
    ]
