# Generated by Django 3.1.3 on 2021-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20210208_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
