# Generated by Django 3.1.3 on 2021-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('day1', models.CharField(max_length=1)),
                ('day2', models.CharField(max_length=1)),
                ('day3', models.CharField(max_length=1)),
                ('day4', models.CharField(max_length=1)),
                ('start_h1', models.PositiveSmallIntegerField()),
                ('start_m1', models.PositiveSmallIntegerField()),
                ('fin_h1', models.PositiveSmallIntegerField()),
                ('fin_m1', models.PositiveSmallIntegerField()),
                ('start_h2', models.PositiveSmallIntegerField()),
                ('start_m2', models.PositiveSmallIntegerField()),
                ('fin_h2', models.PositiveSmallIntegerField()),
                ('fin_m2', models.PositiveSmallIntegerField()),
                ('start_m3', models.PositiveSmallIntegerField()),
                ('start_h3', models.PositiveSmallIntegerField()),
                ('fin_h3', models.PositiveSmallIntegerField()),
                ('fin_m3', models.PositiveSmallIntegerField()),
                ('start_h4', models.PositiveSmallIntegerField()),
                ('start_m4', models.PositiveSmallIntegerField()),
                ('fin_h4', models.PositiveSmallIntegerField()),
                ('fin_m4', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
