# Generated by Django 3.1.3 on 2021-02-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210206_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='index',
        ),
    ]
