# Generated by Django 3.1.3 on 2021-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_subjectinfo_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='day1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day4',
            field=models.CharField(max_length=1),
        ),
    ]
