# Generated by Django 3.1.3 on 2021-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20210206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day1',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day3',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='day4',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='finish_time1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='finish_time2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='finish_time3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='finish_time4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='professor1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='professor2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='start_time1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='start_time2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='start_time3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='start_time4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
