# Generated by Django 3.1.3 on 2021-02-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20210206_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_selected1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subjectinfo')),
            ],
        ),
    ]
