# Generated by Django 3.1.3 on 2021-02-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='added',
        ),
        migrations.RemoveField(
            model_name='subjectinfo',
            name='choice',
        ),
    ]
